### ISSUE TITLE
Generated rbxl files have duplicate services when loaded

### ISSUE THREAD

**Issue by LPGhatguy** [rojo-rbx/rbx-dom#11]
This manifests itself mostly in Rojo -- services aren't tagged with the right piece of metadata in the binary format I don't think, which causes this fun:

![image 11](https://user-images.githubusercontent.com/654598/53136690-b0113500-3534-11e9-9962-fd5ccce197f6.png)

**Comment by Kampfkarren** [comment]
Search the class name in rbx-reflection?

**Comment by LPGhatguy** [comment]
`rbx_reflection` is pretty new relative to `rbx_binary`, but yeah, I think that's the best plan!

**Comment by LPGhatguy** [comment]
Looking into the details of the format from the public sources available, I actually don't see where this metadata would even go. O_o

The additional data byte (defined by [this document](http://www.classy-studios.com/Downloads/RobloxFileSpec.pdf)) isn't set for instances like `Lighting` in the example, but I was certain that would be the cause of this bug!
