### ISSUE TITLE
line 1, column 0: 1:8 Unexpected token inside qualified name: !

### ISSUE THREAD

**Issue by Cobertos** [rojo-rbx/rbx-dom#157]
Roblox Studio version: 0.459.2.415937 (64bit)
OS version: Windows 10 Build 19041

I was using [rbxlx_to_rojo](https://github.com/rojo-rbx/rbxlx-to-rojo/tree/master/src) and tried downloading a place (through Roblox Studio's "Download a Copy...") and converting it, but it isn't able to finish decoding the `.rblx` file.

Here's the output from `rbxlx_to_rojo`:

```console
$ C:\Users\cobertos\Downloads\rbxlx-to-rojo.exe jeff-gaming-3-rojo.rbxl
[2021-01-05T05:08:00Z INFO  rbxlx_to_rojo] rbxlx-to-rojo 0.1.0
[2021-01-05T05:08:00Z INFO  rbxlx_to_rojo] Select a place file.
[2021-01-05T05:08:00Z INFO  rbxlx_to_rojo] Opening place file
[2021-01-05T05:08:00Z INFO  rbxlx_to_rojo] Decoding place file, this is the longest part...
An error occurred while using rbxlx-to-rojo.
While attempting to decode the place file, at line 1, column 0: 1:8 Unexpected token inside qualified name: ! rbx_xml didn't know what to do
```

Looks like .rbxl is binary so not easy for me to debug further and it looking to be an issue from [`rbx_xml::from_reader_default(&rbxlx_source).map_err(Problem::DecodeError)?;`](https://github.com/rojo-rbx/rbxlx-to-rojo/blob/master/src/cli.rs#L99).

Here's the file I couldn't decode:

[jeff-gaming-3-rojo.zip](https://github.com/rojo-rbx/rbx-dom/files/5768266/jeff-gaming-3-rojo.zip)

**Comment by Dekkonot** [comment]
This is a bug with rbxlx-to-rojo; it's using `rbx_xml` to decode a binary file when it should either validate the file extension or give a better error.

This is happening because the first several bytes of both file formats at the same: the xml format starts with `<roblox` and the binary format starts with `<roblox!`.

**Comment by Cobertos** [comment]
Alright, will move over there, thanks
