### ISSUE TITLE
Int32 crash

### ISSUE THREAD

**Issue by Wingysam** [rojo-rbx/rbx-dom#162]
After installing `rbx_util` from cargo, I attempted to convert my XML game build to binary but it failed. This was the error message that I received:
![image](https://user-images.githubusercontent.com/18403742/109174684-1009ca00-7753-11eb-919e-b3e42be830ac.png)

I've sent my game export file to lpg privately.

**Comment by LPGhatguy** [comment]
Fixed in 967343f5e35575f30b093bca11fd51799d6c8ac5!
