### ISSUE TITLE
Crashes when encountering BrickColor

### ISSUE THREAD

**Issue by Wingysam** [rojo-rbx/rbx-dom#164]
Attempting to build my game with Rojo or `rbx-util convert Baseplate.rbxlx Baseplate.rbxl` causes a crash with this BrickColor-having Team.

(zip because GitHub has a whitelist of extensions) [Baseplate.rbxlx.zip](https://github.com/rojo-rbx/rbx-dom/files/6046812/Baseplate.rbxlx.zip)

**Comment by Wingysam** [comment]
Possible dupe of #158?

**Comment by LPGhatguy** [comment]
Fixed in 275ac22e33f6fc0ebc7fce94c84735d626cf20e4.
