### ISSUE TITLE
Missing new type: OptionalCoordinateFrame

### ISSUE THREAD

**Issue by badcc** [rojo-rbx/rbx-dom#167]
When attempting to call `readPlaceFile` on an xml file: 

```
[ERROR] callback error: external error: line 65, column 3: Unknown property type 'OptionalCoordinateFrame': stack traceback:
        [C]: in ?
        [C]: in field 'readPlaceFile'
        [string "test.lua"]:1: in main chunk

Caused by:
    0: external error: line 65, column 3: Unknown property type 'OptionalCoordinateFrame'
    1: line 65, column 3: Unknown property type 'OptionalCoordinateFrame'
```

e.g. `<OptionalCoordinateFrame name="WorldPivotInternal"></OptionalCoordinateFrame>`

(seems to exist for Workspace, and Model)

**Comment by lextoumbourou** [comment]
If you need to get this working in a hurry, you can filter out those lines using grep and it seems to work okay:

```
grep -vwE "OptionalCoordinateFrame" PlaceFile.rbxlx > PlaceFileCleaned.rbxlx
```

**Comment by lextoumbourou** [comment]
Just to clarify with the tag, this is currently causing rbx-dom to return errors, making it unusable files saved with the latest version of Roblox Studio.

So it's not an `enhancement`, more of a `breaking`.

**Comment by Dekkonot** [comment]
Wasn't sure if I should tag it as a bug or what. I ended up on enhancement since it's technically supporting a new feature, but upon further reflection you're right. The tags are mostly superficial anyway, but for the sake of visual clutter I've changed it.

**Comment by Kampfkarren** [comment]
It's alright, it'll get resolved no matter what 😛

**Comment by LPGhatguy** [comment]
We've stopped the bleeding at least. Now, you should just see some warnings whenever this type pops up.

**Comment by Dekkonot** [comment]
This should (hopefully) be resolved; we have a bit of behind the scenes work to do but for users, it won't crash or anything. If you run into new problems, go ahead and open a new issue.

**Comment by RemielDev** [comment]
> If you need to get this working in a hurry, you can filter out those lines using grep and it seems to work okay:
> 
> ```
> grep -vwE "OptionalCoordinateFrame" PlaceFile.rbxlx > PlaceFileCleaned.rbxlx
> ```

Where can I run this?

**Comment by shawnjbragdon-0** [comment]
> > If you need to get this working in a hurry, you can filter out those lines using grep and it seems to work okay:
> > ```
> > grep -vwE "OptionalCoordinateFrame" PlaceFile.rbxlx > PlaceFileCleaned.rbxlx
> > ```
> 
> Where can I run this?

I think it's exclusive to Linux. I don't know how it works but maybe you can try looking for the equivalent for your operating system.
