### ISSUE TITLE
Broken superclass in 4.0.0-alpha?

### ISSUE THREAD

**Issue by jeparlefrancais** [rojo-rbx/rbx-dom#178]
While working on remodel, I tried pulling ClassDescriptors to implement `Instance:IsA()` but I noticed that the `superclass` field seems to be `None`.

For example if I add these tests in some file they both fail

```rust
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_spawnlocation_superclass() {
        let descriptor = ClassDescriptor::new("SpawnLocation");

        assert_eq!(descriptor.superclass, Some("Part".into()));
    }

    #[test]
    fn test_scrolling_frame_superclass() {
        let descriptor = ClassDescriptor::new("ScrollingFrame");

        assert_eq!(descriptor.superclass, Some("GuiObject".into()));
    }
}
```

I just want to confirm that I am not missing something and just doing it wrong! I'm happy to contribute a fix for this 😄

**Comment by kennethloeffler** [comment]
`rbx_reflection` defines types that represent reflection information. If you need the information itself, `rbx_reflection_database` is the crate you want. It contains a pregenerated database that's ready to use!

**Comment by jeparlefrancais** [comment]
So I was missing something! Thanks for your help 😄
