### ISSUE TITLE
">" isn't properly escaped when contained in a string that is exported to rbxm causing import to fail

### ISSUE THREAD

**Issue by eAi** [rojo-rbx/rbx-dom#201]
We're using remodel 0.8.1.

We have a rich-text string in the game that contains <br/> to indicate a line break.

When remodel exports this, it exports it incorrectly: The < is escaped correctly as `&lt;` but the > is not escaped at all. This causes the resulting XML to be invalid and rojo fails to import it. Removing the / before the > doesn't make a difference.

The original rbxlx file contains this:
`<string name="Text">This is some&lt;br/&gt;Text with a new line in</string>`
The generated rbxmx contains this:
`<string name="Text">This is some&lt;br/>Text with a new line in</string>`

Attached is a minimal reproduction of this issue.

I'm not sure if this lies in remodel directly or the underlying libraries it uses - or the underlying xml serialisation libraries they use! I've tried digging through them to find out but it's tricky to follow and I'm not very familiar with rust.

[new-line-bug.zip](https://github.com/rojo-rbx/remodel/files/6829394/new-line-bug.zip)

**Comment by LPGhatguy** [comment]
Related: #202. Seems like xml-rs might have a handful of escaping issues around.

**Comment by NobleDraconian** [comment]
I have a reproduction of this issue if it's of any use.
```bat
rojo build default.project.json -o Temp\Build.rbxlx
remodel run Scripts\AddGameVersion.lua
```

[CharEscapeBug_Repro.zip](https://github.com/rojo-rbx/rbx-dom/files/6871599/CharEscapeBug_Repro.zip)

**Comment by eAi** [comment]
@LPGhatguy The fix for this has now been merged in in xml-rs. The maintainer of that package has also said that he hasn’t any time to work on xml-rs which is why this hasn’t been fixed sooner and that it needs a new maintainer: https://github.com/netvl/xml-rs/pull/195#issuecomment-888779913. Probably not easy, but may be worth looking for a more reliable xml library - or taking over maintaining xml-rs.

**Comment by LPGhatguy** [comment]
This should be fixed on master now after a dependency upgrade. Expect this to make it to Rojo/Remodel soon-ish.
