### ISSUE TITLE
Warning preventing from decoding a .rbxlx file (rbxlx-to-rojo)

### ISSUE THREAD

**Issue by KhanPython** [rojo-rbx/rbx-dom#203]
Resurfaced as I was trying to port an existing .rbxlx place. Perhaps due to the latest update?

`rbx_xml::deserializer] Unknown value type name "OptionalCoordinateFrame" in Roblox XML model file. Found in property Workspace.WorldPivotData.`

P.S. Unsure whether this is the right place for the issue - my apologies in advance

**Comment by LPGhatguy** [comment]
Hello, thanks for filing an issue.

This is just a warning. It doesn't prevent you from doing anything. 😅

We've fixed it in the latest version of rbx_xml and tools will be upgraded in time to properly support `OptionalCoordinateFrame` instead of warning and dropping it.
