### ISSUE TITLE
Rojo 7.0.0 Unknown binary chunk name SSTR

### ISSUE THREAD

**Issue by KazabiteBoltiz** [rojo-rbx/rbx-dom#224]
![image](https://user-images.githubusercontent.com/47039108/168743472-442e69c1-9381-4200-bb78-1c1a5235d361.png)

I don't understand this error. All my dependencies are installed, everything checks out. Maybe this is a Rojo bug?

**Comment by LPGhatguy** [comment]
Rojo 7.0 uses rbx_binary 0.6.4. The error in your screenshot appears to be rbx_binary 0.5.0.

Perhaps you need to update Rojo? Rojo 6.0 uses rbx_binary 0.5.0 and does not have full support for the binary format.
