### ISSUE TITLE
Vector2 turns INF into 0 in rbx_xml

### ISSUE THREAD

**Issue by ohimesan** [rojo-rbx/rbx-dom#237]
I tried importing a rbxmx file today and noticed that the (inf, inf) in my UISizeConstraint got turned into (0, 0)

To replicate, just create an UISizeConstraint, save as a rbxmx, then try to import via Rojo.

**Comment by Dekkonot** [comment]
This appears to be a bug in Rojo, as I'm not able to recreate it with just rbx_xml.

**Comment by Dekkonot** [comment]
Is this still an issue you're encountering @ohimesan?

**Comment by Dekkonot** [comment]
Going to assume no. Please reopen this if you're still having problems.
