### ISSUE TITLE
Type mismatch: Property IntValue.Value should be Int32, but it was Int64

### ISSUE THREAD

**Issue by ThatTimothy** [rojo-rbx/rbx-dom#301]
A bit of background: I've been using [Lune](https://github.com/filiptibell/lune) to convert over some old files into a more usable file system format rather than arbitrary binary files. It seems like some of my older files aren't able to be deserialized.

I can reopen them and save again, and it seems to work fine after that, but I really don't want to do that another 2,000 times. If this is a non-issue, I totally understand lol. It's a very old file from early 2018.

Lune log with `RUST_LOG=trace`:

```lua
local inputFile = fs.readFile("repo.rbxl")
local game = roblox.deserializePlace(inputFile)
print(game.ClassName)
```

```txt
[TRACE rbx_binary::chunk] Chunk "PROP" (compressed: 24, len: 22, reserved: 0)
[TRACE rbx_binary::deserializer::state] PROP chunk (IntValue.Value, instance type 29, prop type 29
[TRACE rbx_binary::deserializer::state] Known prop, canonical name Value and type Int64, with None migration
Failed to read document from buffer - Type mismatch: Property IntValue.Value should be Int32, but it was Int64
```

Remodel log with `RUST_LOG=trace`:
```lua
local game = remodel.readPlaceFile("repo.rbxl")
print(game.ClassName)
```

```txt
[TRACE] Known prop, canonical name Tags and type Tags
[TRACE] Chunk "PROP" (compressed: 24, len: 22, reserved: 0)
[TRACE] PROP chunk (IntValue.Value, instance type 29, prop type 29
[TRACE] Known prop, canonical name Value and type Int64
[ERROR] callback error
        stack traceback:
                [C]: in field 'readPlaceFile'
                [string "remodel.lua"]:1: in main chunk
        caused by: Type mismatch: Property IntValue.Value should be Int32, but it was Int64
```

Repo file: https://github.com/ThatTimothy/rbx-binary-issue-repo/blob/main/repo.rbxl (didn't let me upload directly, sorry)

**Comment by kennethloeffler** [comment]
Given all the information here, it looks like somewhere in between early 2018 and when rbx-dom started supporting the Roblox binary format (late 2020), the serialized type for the `IntValue.Value` property changed from `Int32` to `Int64`. This can probably be patched by adding an arm for `VariantType::Int64` in the `match canonical_type` here: https://github.com/rojo-rbx/rbx-dom/blob/bc1f1543039d5466dca6807ffc1c4a4b6c23edff/rbx_binary/src/deserializer/state.rs#L482

You'll want to `read_interleaved_i64_array` (much like the `VariantType::Int32` arm, except this time reading `i64`s), and convert the values to `i32`, adding them to their respective instances.

I'm not sure if rbx-dom would take this change back upstream - does anyone else want to chime in?

**Comment by ThatTimothy** [comment]
Thanks for looking into this! I'll try implementing my own fork and see if I can get it working.

**Comment by kennethloeffler** [comment]
> You'll want to read_interleaved_i64_array (much like the VariantType::Int32 arm, except this time reading i64s), and convert the values to i32, adding them to their respective instances.

Yeah... so I'm wrong here. I think you'll want exactly the same code as in the `VariantType::Int32` arm, just cast to `i64` when you call `add_property`!

**Comment by ThatTimothy** [comment]
Okay so this is really weird - it's actually the reverse I had to do. I had to, when given Int64, and canonical type is Int32, read it as i32? I would've expected to read it as i64, but that gave a buffer not filled issue, and reading it as i32 fixed it? Further reads and writes perform normally on the current version after it is fixed.

I looked into how migrations currently work and I don't see a easy way to change types, but someone more experienced might be able to figure that out as a better solution.

For what it's worth, here's my quick and dirty solution: https://github.com/ThatTimothy/rbx-dom/tree/int-32-to-int-64-patch
Diff: https://github.com/ThatTimothy/rbx-dom/commit/69b478034eb5d123aecf19f538e812c1b6f98a70

I don't understand why this works, did Roblox decrease the size? That just doesn't make sense that this would fix it.

**Comment by ThatTimothy** [comment]
Nevermind, I think I got it?

It's showing up as Int64 in xml now instead of int, so I think that's good?

```
<Item class="IntValue" referent="1406">
                  <Properties>
                    <string name="Name">GlowRange</string>
                    <BinaryString name="Tags"></BinaryString>
                    <int64 name="Value">6</int64>
                  </Properties>
                </Item>
```

I understand now: canonical type is what we expect from the reflection database (Int64 in this case), vs the binary_type (Int32 in this case). So I had to define a way to get the Int64 type from the Int32 binary type. 

Newest diffs: https://github.com/rojo-rbx/rbx-dom/compare/master...ThatTimothy:rbx-dom:int-32-to-int-64-patch

**Comment by Dekkonot** [comment]
That diff looks good to me, so feel free to open a PR with it.

This needs to be resolved with rbx_xml too, but I've gone ahead and opened #303 since I'm in the process of rewriting that crate.

**Comment by ThatTimothy** [comment]
Cleaned it up a bit and also did a float change as well, I've opened #305 for the rbx_binary version.
