### ISSUE TITLE
Document and implement `Terrain.MaterialColors` support

### ISSUE THREAD

**Issue by Dekkonot** [rojo-rbx/rbx-dom#316]
This is hopefully a self-explanatory issue. `MaterialColors` is a binary property in the same vein as Attributes and Tags, and we should have first-class support for it. This means it should (de)serialize specially like those blobs.

There is an existing spec written by Anaminus located [here](https://github.com/RobloxAPI/spec/blob/master/properties/MaterialColors.md) that we can use as a starter, but we'll have to verify it and I'd also like to document it directly.

**Comment by hoontee** [comment]
Verified that Anaminus' spec is accurate.
