### ISSUE TITLE
`UniqueId::now` fallback default in binary serializer can cause `UniqueId` collisions

### ISSUE THREAD

**Issue by kennethloeffler** [rojo-rbx/rbx-dom#324]
While investigating filiptibell/lune#69, I found that the current usage of `UniqueId::now` in `SerializerState::fallback_default_value` can cause `UniqueId` collisions. This occurs when multiple instances of the same class exist in a `WeakDom`, and some of the instances contain `UniqueId` properties, while others do not. 

It looks like the reason why is that in the serializer, one `TypeInfo` is created for each class:
https://github.com/rojo-rbx/rbx-dom/blob/d9bf893dfdf15ff60c68bab404f5af71c6e880df/rbx_binary/src/serializer/state.rs#L268-L295

The fallback defaults are then reused among all instances of the class:
https://github.com/rojo-rbx/rbx-dom/blob/d9bf893dfdf15ff60c68bab404f5af71c6e880df/rbx_binary/src/serializer/state.rs#L524-L574

I verified this by running the repro in filiptibell/lune#69 with a version of rbx_binary that uses the "nil `UniqueId`" for the fallback default (all zeros - which Roblox will happily load, even if there are other nil `UniqueId`s)

**Comment by Dekkonot** [comment]
I think the obvious fix here is to not serialize UniqueId at all for now, since it results in diff noise anyway. Beyond that though, we can change to using the nil `UniqueId` as a default since it's safe. What are your thoughts?

**Comment by kennethloeffler** [comment]
Dunno, I'm gonna leave that call up to you. I think it'll be easy enough to do either
