### ISSUE TITLE
Failed to deserialize Configuration.AttributesSerialize

### ISSUE THREAD

**Issue by krakow10** [rojo-rbx/rbx-dom#395]
I am getting a deserialization error when using rbx_binary and rbx_xml.  I have located the problem object and exported some files:
[configuration.rbxm](https://github.com/rojo-rbx/rbx-dom/files/14381788/configuration.rbxm.txt)
[configuration.rbxmx](https://github.com/rojo-rbx/rbx-dom/files/14381789/configuration.rbxmx.txt)

This is the exact error message it prints when using rbx_binary v0.7.4:
```
[quat@quat-desktop history]$ ~/git/asset-tool/target/release/asset-tool --style rox-rojo --no-template true --no-models true --input ../configuration.rbxm --output . decompile
Error: Failed to deserialize Configuration.AttributesSerialize because invalid value type: 21
```

This is the exact error message it prints when using rbx_xml v0.13.3:
```
[quat@quat-desktop history]$ ~/git/asset-tool/target/release/asset-tool --style rox-rojo --no-template true --no-models true --input ../configuration.rbxmx --output . decompile
Error: line 16, column 31: Property Configuration.Attributes is expected to be of type Attributes, but it was of type BinaryString When trying to convert, this error occured: Unknown or invalid Attributes
```

This is how the object appears in studio:
![image](https://github.com/rojo-rbx/rbx-dom/assets/3529698/53573712-5095-48f1-b71e-0616616b10a8)

The values appear to be Enums:
![image](https://github.com/rojo-rbx/rbx-dom/assets/3529698/c21f0bd7-247d-48a0-8053-26437415e1f3)

**Comment by Dekkonot** [comment]
Howdy! Thanks for the report. We're tracking enum attributes in #383. I suppose we'll move them up in our agenda if they're being found out in the wild now!

Because this is being tracked elsewhere, I'm going to close this in favor of that issue though.
