### ISSUE TITLE
Serve still incorrectly changes WorldPivotData

### ISSUE THREAD

**Issue by TRHeliad** [rojo-rbx/rbx-dom#413]
I'm not sure if rojo-rbx/rojo#865 was meant to fix both building and syncing/serving pivots, but I seem to still be having this issue.
If you test this [this](https://github.com/rojo-rbx/rbx-dom/files/15396705/PivotRepro.zip) project, building will result in having the correct pivot and position for the model, but syncing will shift it significantly. For me it shifts the origin from `-892.671, 34.276, -539.095` to `-697.9, 38.428, -386.246`.

---
![image](https://github.com/rojo-rbx/rbx-dom/assets/32373868/737dff64-585c-478a-88d7-e0c1d15db4f3)

**Comment by Dekkonot** [comment]
I believe this was resolved via #408. It's not currently released yet though. Going to close this, but feel free to open an issue in Rojo's repo so that we can track this bug.
