### ISSUE TITLE
Small Inconsistency with float & double in Attributes encoding

### ISSUE THREAD

**Issue by phoriah** [rojo-rbx/rbx-dom#421]
In your documentation it's mentioned that Studio isn't capable of producing float-type attributes. This is mostly true.
https://github.com/rojo-rbx/rbx-dom/blob/f6007d561bcde2d120922cec818c0765a00ec460/docs/attributes.md?plain=1#L78
However, it seems that if you were to add an Attribute using the Studio properties menu:
![image](https://github.com/rojo-rbx/rbx-dom/assets/95628489/a9e6d890-bd91-4004-af63-2e844dc96eb9)
And then save the file as xml (for example), you'd notice that the string encodes as `AQAAAAYAAABudW1iZXIFAAAAAA==` which, when decoded, show that it has a Type ID of `0x05` and has a size of a `float`. 
Though, if you were to touch the value in any way, it would convert to a `0x06` and use `double`'s format. 

I'm not sure if this breaks any of your code but it's an interesting exception and might be worth taking into count.
Correct me if I'm wrong.

**Comment by Dekkonot** [comment]
...I'll verify this Monday but if this is actually the case, I'll be confused.

Does this happen for binary files do you know?
